@startuml
class com.example.projekcik.UserPanelController {
- String loginuzytkownika
- Set<Integer> zaznaczoneProdukty
- TextField szukanieField
- Label loginLabel
- Label saldoLabel
+ VBox dodajpanel2
+ VBox dodajpanel3
+ VBox dodajpanel4
+ VBox dodajpanel5
+ TextField cenacalkowitaField
+ TextField wplataField
+ TableView<Produkt> widok
+ TableColumn<Produkt,Boolean> zaznaczField
+ TableColumn<Produkt,String> nazwaproduktuField
+ TableColumn<Produkt,Integer> iloscproduktuField
+ TableColumn<Produkt,Number> cenaproduktuField
+ TableColumn<Produkt,String> opisproduktuField
+ TableView<Produkt> widokkoszyka
+ TableColumn<Produkt,Integer> koszykiloscproduktudozakupuField
+ TableColumn<Produkt,String> koszyknazwaproduktuField
+ TableColumn<Produkt,Integer> koszykiloscproduktuField
+ TableColumn<Produkt,Number> koszykcenaproduktuField
+ TableColumn<Produkt,Boolean> usuncheckbox
+ TableView<Zamowienie> widokzamowien
+ TableColumn<Zamowienie,String> statusField
+ TableColumn<Zamowienie,Number> cenazamowieniaField
+ TableColumn<Zamowienie,java.util.Date> datazamowieniaField
+ void ukryjpanel()
+ void pokazpanel(VBox)
+ void dodajsrodki()
+ void wplacsrodki()
+ void wyswietlogin(String)
+ void wyswietlsaldo()
+ void kupprodukt()
+ void pokazzamowieniapanel()
+ void pokazprodukty()
+ void wyswietlkoszyk()
+ void zakup()
+ void usunzkoszyka()
+ void zaaktualizujcene()
+ ObservableList<Produkt> Wyswietlprodukty()
+ void Wstecz()
+ void wyloguj()
+ void pokazzamowieniaklienta()
+ void szukanieproduktow()
- void ListenerDoZaznaczen(ObservableList<Produkt>)
}


class com.example.projekcik.Produkt {
- BooleanProperty zaznaczony
- BooleanProperty zaznaczonydousuniecia
- IntegerProperty iloscdozakupu
- Integer id_produktu
- String nazwa
- double cena
- Integer ilosc
- String opis
+ Integer getId_produktu()
+ void setId_produktu(Integer)
+ int getIloscdozakupu()
+ void setIloscdozakupu(int)
+ IntegerProperty IloscdozakupuProperty()
+ boolean isZaznaczonydousuniecia()
+ void setZaznaczonydousuniecia(boolean)
+ BooleanProperty zaznaczonydousunieciaProperty()
+ boolean isZaznaczony()
+ BooleanProperty zaznaczonyProperty()
+ void setZaznaczony(boolean)
+ String getNazwa()
+ void setNazwa(String)
+ String getOpis()
+ void setOpis(String)
+ Integer getIlosc()
+ void setIlosc(Integer)
+ double getCena()
+ void setCena(double)
}


class com.example.projekcik.Administrator {
+ String Wyswietlrola()
}

class com.example.projekcik.Osoba {
- String rola
- Integer id_klienta
- String login
- String imie
- String nazwisko
- String email
- String adres
+ Integer getId_klienta()
+ void setId_klienta(Integer)
+ String getRola()
+ void setRola(String)
+ String getLogin()
+ void setLogin(String)
+ String getImie()
+ void setImie(String)
+ String getEmail()
+ void setEmail(String)
+ String getNazwisko()
+ void setNazwisko(String)
+ String getAdres()
+ void setAdres(String)
+ String Wyswietlrola()
}


class com.example.projekcik.Uzytkownik {
+ String Wyswietlrola()
}

class com.example.projekcik.DB.UserDAO {
+ void dodajUzytkownika(String,String,String,String,int,String,String)
+ boolean UzytkownikIstnieje(String)
+ boolean EmailIstnieje(String)
+ boolean ZalogujUzytkownik(String,String)
+ boolean ZalogujAdministrator(String,String)
+ double Wyswietlsaldo(String)
+ void dodajProdukt(String,double,Integer,String)
+ List<Produkt> pokazProdukty()
+ void depozyt(String,double)
+ void usunprodukt(int)
+ void zakup(String,double)
+ void zaaktualizujiloscproduktu(int,int)
+ int znajdzuzytkownikapologinie(String)
+ void dodajzamowienie(int,Date,String,double)
+ List<Zamowienie> pokazzamowieniawszystkich()
+ List<Zamowienie> pokazzamowieniaklienta(String)
+ List<Osoba> pokazuzytkownikow()
+ List<Produkt> szukajProdukt(String)
}

class com.example.projekcik.LoginController {
+ TextField loginField
+ PasswordField passwordField
# void Login()
- void logowanie(FXMLLoader)
# void Register()
}


class com.example.projekcik.RegisterController {
+ TextField usernameField
+ TextField firstNameField
+ TextField lastNameField
+ TextField emailField
+ TextField addressField
+ TextField ageField
+ PasswordField passwordField
+ void WyczyscPola()
# void Zalozkonto()
# void Mamkonto()
}


class com.example.projekcik.Main {
+ void start(Stage)
+ {static} void main(String[])
}

class com.example.projekcik.DB.DBConnection {
- {static} String URL
- {static} String USER
- {static} String PASSWORD
+ {static} Connection getConnection()
}


class com.example.projekcik.AdminPanelController {
- Label roleLabel
- Label loginLabel
+ VBox dodajpanel
+ VBox dodajpanel2
+ VBox dodajpanel3
+ VBox dodajpanel4
+ TextField nazwaField
+ TextField cenaField
+ TextField iloscField
+ TextArea opisField
+ TableView<Zamowienie> widokzamowien
+ TableColumn<Zamowienie,String> statusField
+ TableColumn<Zamowienie,Number> cenazamowieniaField
+ TableColumn<Zamowienie,String> loginuzytkownikaField
+ TableColumn<Zamowienie,String> imieField
+ TableColumn<Zamowienie,String> nazwiskoField
+ TableColumn<Zamowienie,Date> datazamowieniaField
+ TableView<Produkt> widok
+ TableColumn<Produkt,Boolean> zaznaczField
+ TableColumn<Produkt,String> nazwaproduktuField
+ TableColumn<Produkt,Integer> iloscproduktuField
+ TableColumn<Produkt,Number> cenaproduktuField
+ TableColumn<Produkt,String> opisproduktuField
+ TableView<Osoba> widokuzytkownikow
+ TableColumn<Osoba,Integer> id_klientaField
+ TableColumn<Osoba,String> loginklientaField
+ TableColumn<Osoba,String> imieklientaField
+ TableColumn<Osoba,String> nazwiskoklientaField
+ TableColumn<Osoba,String> emailklientaField
+ TableColumn<Osoba,String> adresklientaField
+ void ukryjpanel()
+ void pokazpanel(VBox)
+ void wyswietlogin(String)
+ void dodajprodukt()
+ void dodaj()
+ void wyczysc()
+ void pokazproduktyitem()
+ void pokazprodukty()
+ void usunprodukt()
+ void pokazzamowieniapanel()
+ void pokazzamowienia()
+ void wyloguj()
+ void pokazklientowpanel()
- void pokazklientow()
}


class com.example.projekcik.Zamowienie {
- int id_zamowienia
- double cena_zamowienia
- String status_zamowienia
- String login
- String imie
- String nazwisko
- Date data_zamowienia
+ double getCena_zamowienia()
+ void setCena_zamowienia(double)
+ String getStatus_zamowienia()
+ void setStatus_zamowienia(String)
+ String getLogin()
+ void setLogin(String)
+ String getImie()
+ void setImie(String)
+ String getNazwisko()
+ void setNazwisko(String)
+ Date getData_zamowienia()
+ void setData_zamowienia(Date)
+ int getId_zamowienia()
+ void setId_zamowienia(int)
}




com.example.projekcik.LoginController <|-- com.example.projekcik.UserPanelController
com.example.projekcik.Osoba <|-- com.example.projekcik.Administrator
com.example.projekcik.Osoba <|-- com.example.projekcik.Uzytkownik
com.example.projekcik.LoginController <|-- com.example.projekcik.RegisterController
javafx.application.Application <|-- com.example.projekcik.Main
com.example.projekcik.LoginController <|-- com.example.projekcik.AdminPanelController
@enduml